// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJfN1PohCetQYuUChymfNJAsNI8H9osFg',
    appId: '1:823708949527:android:ae74210635734df8785052',
    messagingSenderId: '823708949527',
    projectId: 'hami-app-197c9',
    databaseURL: 'https://hami-app-197c9-default-rtdb.firebaseio.com',
    storageBucket: 'hami-app-197c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9mK4BqOufPvqe1H8Qu93jh6ePn3BmfOs',
    appId: '1:823708949527:ios:2c4f3e1df38ea81e785052',
    messagingSenderId: '823708949527',
    projectId: 'hami-app-197c9',
    databaseURL: 'https://hami-app-197c9-default-rtdb.firebaseio.com',
    storageBucket: 'hami-app-197c9.firebasestorage.app',
    iosClientId: '823708949527-8lsvmr0hucpqo0qe78tu5habdcahs2i7.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliverblesApp',
  );
}
